### ISSUE TITLE
using the json-traverse parser to set values

### ISSUE THREAD

**Issue by greg-k-taylor** [EmilStenstrom/json-traverse#2]
Thank you for publishing this parser - the logic has been helpful to read through.

I would like to extend the json-traverse parser to set values specified by a path.  I have created a child class that takes a raw python object as an input parameter (instead of json-text).  I would then like to call something like the following:

parser.traverse_set("database.pharmacology.xref.wikipedia", "www.myurl.com")

Do you have any advice or insights for writing this method?  I think that it would be broadly useful.

**Comment by EmilStenstrom** [comment]
While adding the possibility to change things with json-traverse is an interesting idea, I think you might be better of looking at a separate library that has this built in: glom. Have a look at the assign method here: https://glom.readthedocs.io/en/latest/api.html#target-mutation-with-assign

Does that look like what you are trying to accomplish?

**Comment by greg-k-taylor** [comment]
Thank for the glom reference.  I am looking into that approach.
